### ISSUE TITLE
ActionViewTemplateError when record is not found in a view

### ISSUE THREAD

**Issue by GuilleLeopold** [rootstrap/rails_api_base#134]
When: 
When trying to call a helper method inside a view and the helper hasn't been called before

What:
If the record is not found, it raises an error that it's catched by the `render_error`  method in the ApiController instead of the `render_record_not_found` method. 

Why:
When raising the error in the view, instead of raising an ActiveRecord:RecordNotFound error, it's raising an `ActionViewTemplateError` and that's why is not being catched by the `render_record_not_found`

For further details, ask @jdrosales17 who is the one that found the issue

**Comment by santiagovidal** [comment]
Fixed by https://github.com/rootstrap/rails_api_base/pull/135
