### ISSUE TITLE
Add Pagy as default pagination gem

### ISSUE THREAD

**Issue by jpascual1994** [rootstrap/rails_api_base#191]
I'm creating this issue to keep track of the idea of adding [Pagy](https://github.com/ddnexus/pagy) as the default pagination gem.

Feel free to discuss other alternatives like [Kaminari](https://github.com/kaminari/kaminari), [Will Paginate](will_paginate), etc

**Comment by juanmanuelramallo** [comment]
👍 for using Pagy
