### ISSUE TITLE
Update code_analysis task to run analysis on the whole codebase

### ISSUE THREAD

**Issue by juanmanuelramallo** [rootstrap/rails_api_base#226]
## Why
Because we want to run Rubocop, Reek (any other analysis) on the whole codebase, not just on specific folders; so that we enforce best practices across all the codebase

## What
Update our code_analysis rake task to run the analysis on all the files, in other words in the root directory

**Comment by juan-apa** [comment]
@juanmanuelramallo can this issue be closed now?

**Comment by juanmanuelramallo** [comment]
Yes!
