### ISSUE TITLE
Password confirmation is not being used

### ISSUE THREAD

**Issue by colembolos** [rootstrap/rails_api_base#244]
## Bug report:
When sign up a user it's not validated the password confirmation

* **Expected Behavior**:
When we send a wrong password confirmation should return an error
 
* **Actual Behavior**: 
Is not being validated

* **Steps to Reproduce**: 
  1. Send different password and password confirmation
  2. The user is been register

* **Version of the repo**: 1.1.2

**Comment by jpascual1994** [comment]
Could you add an example?
We have a test for this case and it isn't failing

**Comment by colembolos** [comment]
> Could you add an example?
> We have a test for this case and it isn't failing

If it was tested maybe there was confusion when I worked with the FE and is not a BE problem
