### ISSUE TITLE
[FEATURE] Support Font Awesome Pro

### ISSUE THREAD

**Issue by sjieg** [rootstrap/rails_api_base#262]
**Is your feature request related to a problem? Please describe.**
See #260 We include Font Awesome Free to let the icons work.

In the CSS code font family is hard defined:
```
font-family: 'Font Awesome Free 5';
```

**Describe the solution you'd like**

At all places where `Font Awesome Free 5` is used, `Font Awesome Pro 5` should also be included. For example:

```
  font-family: 'Font Awesome Free 5';
  font-weight: 900;
```

Should become

```
  font-family: 'Font Awesome Free 5', 'Font Awesome Pro 5';
  font-weight: 900;
```

This way both versions of Font Awesome should work:
```
<i class="fa-users" style="font-family: 'Font Awesome 5 Free'; font-weight: 900;"></i> Free
<br />
<i class="fa-users" style="font-family: 'Font Awesome 5 Pro'; font-weight: 900;"></i> Pro
<br />
<i class="fa-users" style="font-family: 'Font Awesome 5 Free', 'Font Awesome 5 Pro'; font-weight: 900;"></i> Both
```

**Describe alternatives you've considered**

Maybe the proper fix would be an ArcticAdmin or ActiveAdmin config setting in `/config/initializers/active_admin.rb`. But in that case it should be engineerd in a way that it will support other icon types as well.

For now I think hard-coding support for both `free` and `pro` is the easiest acceptable fix.

**NOTE**

If you want I can make the PR. First I'd like to hear if this is an acceptable feature.

**Comment by santib** [comment]
Hey @sjieg thanks for submitting the issue. Given that font awesome pro is paid, I think we should not get it included by default in a base app like this one. In particular, the npm package is private and requires a subscription, so it might not even be possible to get it installed.

![image](https://user-images.githubusercontent.com/6373536/94453961-b000fe80-0187-11eb-83d5-6adab4642210.png)

What are your thoughts on this?

**Comment by sjieg** [comment]
Hey @santib thanks for your response.

After writing a more detailed response, I found out that someshow I thought I was creating a ticket for arctic_admin. I think because of the reference from #260 .

My bad! I'll recreate on the correct repository. Keep up the good work :)
