### ISSUE TITLE
Update status endpoint to support non-json requests

### ISSUE THREAD

**Issue by martinjaimem** [rootstrap/rails_api_base#273]
Amazon tools to check if a container is up and running tend to check if a `get` to a certain URL returns 200. So, in that case, we won't be able to check that unless we change the status endpoint to accept non-json requests.

[An example.](https://github.com/rootstrap/takion-api/commit/f71bd007e4f1bc8b91093f8e285ccb28efe6b6e0)

**Comment by juanmanuelramallo** [comment]
I think we already support this via #250, don't we?
