### ISSUE TITLE
Set bundler version on Dockerfile

### ISSUE THREAD

**Issue by martinjaimem** [rootstrap/rails_api_base#280]
Right now there is a step in the Dockerfile that does:
```
RUN gem install bundler
```

the problem here is that we could be building two images with the same Dockerfile and expect different results depending on the time they were created.

Solution:

replace:

```
RUN gem install bundler
```

with:

```
RUN gem install bundler:2.2.0
```

**Comment by santib** [comment]
I think the bundler version from the `Gemfile.lock` is used, so this shouldn't be an issue.
