### ISSUE TITLE
Authentication problems with Token

### ISSUE THREAD

**Issue by StephanSinn** [rootstrap/rails_api_base#288]
## Bug report:
* **Expected Behavior**: 
* Authentication of User at Get Request by Token
* **Actual Behavior**: 
* Authentication fails
* **Steps to Reproduce**: 
  1. Use Postman to test API after installation with Docker.
  2. Here is the link for the devise postman collection: https://app.getpostman.com/run-collection/03eb9dc02659fe7b85b5
  3. Sign In works fine!
  4. Transfer of Header Information to GET /api/v1/user results into Error 401 :authenticat user!

* **Version of the repo**: v1.1.2
* **Ruby and Rails Version**: 6.0.0
* **Rails Stacktrace**: this can be found in the `log/development.log` or `log/test.log`, if this is applicable.

Sorry, maybe I am just too stupid, since I am new to API dev. But I couldn't manage to make it working for the GET request, when the User has to be logged in. I used Postman to test the api you provide, when docker-compose is runnning. 

First Step I Sign In to get the header information:
![grafik](https://user-images.githubusercontent.com/41671832/105853995-9614e280-5fe6-11eb-9342-82a98f184f99.png)

Afterwards I transferred the header information to make the GET request, I followed the test results in the doc, here the excerpt from the doc/api/index.apib:

### Show [GET]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: donovan@bergnaum-beahan.biz

+ Response 200 ()

    + Headers

            access-token: 1234567890123456789012
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry: 1674678792
            uid: donovan@bergnaum-beahan.biz

    + Body

            {
              "user": {
                "id": 65,
                "email": "donovan@bergnaum-beahan.biz",
                "name": "Archie Sporer Wiza",
                "username": "rosalva_hammes"
              }
            }

So my request in Postman looked like this, resulting in the desribed error:
![grafik](https://user-images.githubusercontent.com/41671832/105853756-54843780-5fe6-11eb-94bc-dd5dc92c5e8c.png)

Here is the curl from the GET:

curl --location --request GET 'http://192.168.178.55:3000/api/v1/user' \
--header 'access-token: inU9lE7mtsNRR_95vIjSlw' \
--header 'token-type: Bearer' \
--header 'client: LoG7qMywac3dddAxduVc8g' \
--header 'expiry: 1674736984' \
--header 'uuid: user@example.com'

What am I doing wrong? I searched through the web, but all problems that commonly occur with devise and devise_token_auth seems to be taken into account in this repo by following the best practices. Sorry if it is a stupid question, but hope you can help me. 

Thanks,
Stephan

**Comment by santir489** [comment]
Hi @StephanSinn. Yo seem to have a typo in `--header 'uuid: user@example.com'`
Can you try if changing `uuid` for `uid` solves the problem?

**Comment by StephanSinn** [comment]
Hi @santir489 , thank you so much! I learned a lot by resolving all errors I did prior to this one that I did not see this typo. Thanks, it works fine! And thanks to the entire team for providing this great boilerplate! I  am sorry for this stupid question, but thanks to you I am now a little bit smarter than before^^.
Cheers,
Stephan
