### ISSUE TITLE
Use I18n

### ISSUE THREAD

**Issue by falvariza** [rootstrap/rails_api_base#47]
Use it in every text that is going to be used. For example, error messaging in `ApiController`

**Comment by matiasmansilla1989** [comment]
@MaicolBen Don't forget error messages, I mean record errors like `Name can't be blank`. Also, what about the admin?
Regarding your question, `api.sessions.unauthorized` is ok for me.

**Comment by MaicolBen** [comment]
@matiasmansilla1989 That's done in `ActiveRecord`, so we can't change anything in the API base.
I don't think is worth to add i18n to the admin, but if you want, we should add it.
