### ISSUE TITLE
Devise Token Auth Registration Create always defaults request format to */* instead of json

### ISSUE THREAD

**Issue by Zinssmeister** [rootstrap/rails_api_base#593]
## Bug report:
* **Expected Behavior**:  I expected the registration of a new user to work by simply making a request to POST `/api/v1/users` and supplying a valid data payload and setting the content-type header to application/json
* **Actual Behavior**: I was setting up a fresh Rails API Base project and noticed that the registration create endpoint keeps defaulting the request format to `*/*` even though the request header content-type: application/json is set.
* **Steps to Reproduce**: 
  1. Make a POST request to /api/v1/users with content-type set to application/json
  2. Rails will return a Can't verify CSRF token authenticity error.
  3. Rails server logs will show: `...method=POST path=/api/v1/users format=*/* controller=API::V1::RegistrationsController...`

* **Version of the repo**: Current Version
* **Ruby and Rails Version**:  7.0.8
* **Rails Stacktrace**: `Can't verify CSRF token authenticity.
method=POST path=/api/v1/users format=*/* controller=API::V1::RegistrationsController action=create status=422 allocations=1346 duration=0.91 view=0.00 db=0.00 host=localhost query_string= referer= user_agent=ActionController::InvalidAuthenticityToken - Can't verify CSRF token authenticity`

**Comment by santib** [comment]
Hi @Zinssmeister,

I agree this is confusing. In order to work, the header `Accept: 'application/json'` needs to be sent by the client. 

I just tried creating a vanilla rails api and confirmed that the header isn't needed there, so I'd like to match the default rails behavior. Are you interested in working on a fix?

**Comment by santib** [comment]
I agree it seems to be related to `DeviseTokenAuth::ApplicationController` inheriting from `DeviseController`.

I did try some things but none of them worked.. So maybe we could go with that solution you found 👍

**Comment by santib** [comment]
Fixed by #600
