### ISSUE TITLE
Make easy to login with other methods like username

### ISSUE THREAD

**Issue by MaicolBen** [rootstrap/rails_api_base#69]
Right now you have to paste a huge method from the sessions controller from devise token auth and remove the constraint: `q = “#{field.to_s} = ? AND provider=‘email’“`, it will be great if the [method is split](https://github.com/lynndylanhurley/devise_token_auth/pull/661), but the maintainers of the gem aren't active as before. Maybe we should paste the code to our sessions controller

**Comment by MaicolBen** [comment]
Now that we have https://github.com/rootstrap/devise_token_auth/, it's needed to create a PR there and create a method that make this `q = "#{field} = ? AND provider = 'username'"` dynamic (where username is a method call or something that can be overridable in the controller)

**Comment by MaicolBen** [comment]
Fixed on https://github.com/rootstrap/devise_token_auth/pull/2, you need to override the `provider` function in the sessions controller

**Comment by dannymockaitis** [comment]
So how do you do this?

**Comment by MaicolBen** [comment]
Check https://github.com/rootstrap/rails_api_base/wiki/How-to-use-another-provider-like-username-to-authenticate
