### ISSUE TITLE
Devise Token Auth Issue: IndexError: string not matched

### ISSUE THREAD

**Issue by MaicolBen** [rootstrap/rails_api_base#73]
It is wrong closed in https://github.com/lynndylanhurley/devise_token_auth/issues/681, the workaround is https://stackoverflow.com/questions/38424068/devise-token-auth-rails-5-indexerror-string-not-matched

**Comment by MaicolBen** [comment]
Fixed with #85

**Comment by MaicolBen** [comment]
This happens also when the user logouts, we need to find the root cause of the problem, for now, you can apply this solution:
```
User.find_each |user|
  user.uid = user.email
  user.tokens = nil
  user.save!
end
```

**Comment by fedeagripa** [comment]
@santib closing this cause the root cause was adding token as `text` instead of `json` that  de serializable and so no error occur
