### ISSUE TITLE
Several database queries happening after processing the request

### ISSUE THREAD

**Issue by santiagovidal** [rootstrap/rails_api_base#86]
After the server processes the request and renders the Jbuilder view, the server performs several queries to the `users` table and it's not clear why it's doing that. It also appears to do a transaction even though it doesn't perform an update on the database.

Below there's a screenshot of the server output:
![screen shot 2017-09-14 at 4 17 09 pm](https://user-images.githubusercontent.com/11350611/30452469-29bf391c-996c-11e7-8c9e-7dad1b0dded3.png)

**Comment by anthfb** [comment]
This seems to be generated by an "exists?" method.  

We should not rely in the other that the logs appear in the console, they were probably executed before rendering the output.

**Comment by MaicolBen** [comment]
It's done [in an after action in the auth gem](https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/concerns/set_user_by_token.rb#L87) in order to update the headers (also, it reloads the user so it doesn't save the headers after logout).
